posts:          /actualites/:year/:month/:day/:slug/
categories:     /actualites/:slug/
persons:        /equipe/:slug/
authors:        /equipe/:slug/actualites/
researchers:    /equipe/:slug/articles/
