posts:          /actualites2/:year/:month/:day/:slug/
categories:     /actualites2/:slug/
persons:        /equipe/:slug/
authors:        /equipe/:slug/actualites2/
administrators: /equipe/:slug/roles/
teachers:       /equipe/:slug/programs/
